/**
 * Central RBAC definition. Roles and permissions are seeded from these constants,
 * so the database and the runtime guards never drift apart.
 */

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  OPERATIONS_MANAGER: 'OPERATIONS_MANAGER',
  CONTROL_ROOM_OPERATOR: 'CONTROL_ROOM_OPERATOR',
  FIELD_SUPERVISOR: 'FIELD_SUPERVISOR',
  ANALYST: 'ANALYST',
  PARTNER_USER: 'PARTNER_USER',
} as const;

export type RoleKey = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_METADATA: Record<RoleKey, { name: string; arabicName: string }> = {
  SUPER_ADMIN: { name: 'Super Admin', arabicName: 'مدير النظام' },
  ORG_ADMIN: { name: 'Organization Admin', arabicName: 'مدير الجهة' },
  OPERATIONS_MANAGER: { name: 'Operations Manager', arabicName: 'مدير العمليات' },
  CONTROL_ROOM_OPERATOR: { name: 'Control Room Operator', arabicName: 'مشغل غرفة العمليات' },
  FIELD_SUPERVISOR: { name: 'Field Supervisor', arabicName: 'مشرف ميداني' },
  ANALYST: { name: 'Analyst', arabicName: 'محلل' },
  PARTNER_USER: { name: 'Partner User', arabicName: 'مستخدم شريك' },
};

// resource:action permission keys
export const PERMISSIONS = {
  ORG_MANAGE: 'organizations:manage',
  ORG_READ: 'organizations:read',
  USERS_MANAGE: 'users:manage',
  USERS_READ: 'users:read',
  VENUES_MANAGE: 'venues:manage',
  VENUES_READ: 'venues:read',
  ZONES_MANAGE: 'zones:manage',
  ZONES_READ: 'zones:read',
  GATES_MANAGE: 'gates:manage',
  GATES_READ: 'gates:read',
  EVENTS_MANAGE: 'events:manage',
  EVENTS_READ: 'events:read',
  CROWD_READ: 'crowd:read',
  QUEUES_READ: 'queues:read',
  ALERTS_MANAGE: 'alerts:manage',
  ALERTS_READ: 'alerts:read',
  INCIDENTS_MANAGE: 'incidents:manage',
  INCIDENTS_READ: 'incidents:read',
  TASKS_MANAGE: 'tasks:manage',
  TASKS_READ: 'tasks:read',
  SIMULATIONS_MANAGE: 'simulations:manage',
  REPORTS_READ: 'reports:read',
  PARTNERS_READ: 'partners:read',
  AUDIT_READ: 'audit:read',
  INTEGRATIONS_MANAGE: 'integrations:manage',
  DASHBOARD_READ: 'dashboard:read',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

// Role → permission grants.
export const ROLE_PERMISSIONS: Record<RoleKey, PermissionKey[]> = {
  SUPER_ADMIN: ALL_PERMISSIONS,
  ORG_ADMIN: [
    PERMISSIONS.ORG_READ,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.VENUES_MANAGE,
    PERMISSIONS.VENUES_READ,
    PERMISSIONS.ZONES_MANAGE,
    PERMISSIONS.ZONES_READ,
    PERMISSIONS.GATES_MANAGE,
    PERMISSIONS.GATES_READ,
    PERMISSIONS.EVENTS_MANAGE,
    PERMISSIONS.EVENTS_READ,
    PERMISSIONS.CROWD_READ,
    PERMISSIONS.QUEUES_READ,
    PERMISSIONS.ALERTS_MANAGE,
    PERMISSIONS.ALERTS_READ,
    PERMISSIONS.INCIDENTS_MANAGE,
    PERMISSIONS.INCIDENTS_READ,
    PERMISSIONS.TASKS_MANAGE,
    PERMISSIONS.TASKS_READ,
    PERMISSIONS.SIMULATIONS_MANAGE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.PARTNERS_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.INTEGRATIONS_MANAGE,
    PERMISSIONS.DASHBOARD_READ,
  ],
  OPERATIONS_MANAGER: [
    PERMISSIONS.VENUES_READ,
    PERMISSIONS.ZONES_READ,
    PERMISSIONS.GATES_MANAGE,
    PERMISSIONS.GATES_READ,
    PERMISSIONS.EVENTS_MANAGE,
    PERMISSIONS.EVENTS_READ,
    PERMISSIONS.CROWD_READ,
    PERMISSIONS.QUEUES_READ,
    PERMISSIONS.ALERTS_MANAGE,
    PERMISSIONS.ALERTS_READ,
    PERMISSIONS.INCIDENTS_MANAGE,
    PERMISSIONS.INCIDENTS_READ,
    PERMISSIONS.TASKS_MANAGE,
    PERMISSIONS.TASKS_READ,
    PERMISSIONS.SIMULATIONS_MANAGE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.DASHBOARD_READ,
  ],
  CONTROL_ROOM_OPERATOR: [
    PERMISSIONS.VENUES_READ,
    PERMISSIONS.ZONES_READ,
    PERMISSIONS.GATES_READ,
    PERMISSIONS.EVENTS_READ,
    PERMISSIONS.CROWD_READ,
    PERMISSIONS.QUEUES_READ,
    PERMISSIONS.ALERTS_MANAGE,
    PERMISSIONS.ALERTS_READ,
    PERMISSIONS.INCIDENTS_MANAGE,
    PERMISSIONS.INCIDENTS_READ,
    PERMISSIONS.TASKS_READ,
    PERMISSIONS.DASHBOARD_READ,
  ],
  FIELD_SUPERVISOR: [
    PERMISSIONS.ZONES_READ,
    PERMISSIONS.EVENTS_READ,
    PERMISSIONS.CROWD_READ,
    PERMISSIONS.INCIDENTS_READ,
    PERMISSIONS.TASKS_MANAGE,
    PERMISSIONS.TASKS_READ,
  ],
  ANALYST: [
    PERMISSIONS.VENUES_READ,
    PERMISSIONS.ZONES_READ,
    PERMISSIONS.EVENTS_READ,
    PERMISSIONS.CROWD_READ,
    PERMISSIONS.QUEUES_READ,
    PERMISSIONS.ALERTS_READ,
    PERMISSIONS.INCIDENTS_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.PARTNERS_READ,
    PERMISSIONS.DASHBOARD_READ,
  ],
  PARTNER_USER: [PERMISSIONS.PARTNERS_READ, PERMISSIONS.QUEUES_READ],
};

export function permissionParts(key: string): { resource: string; action: string } {
  const [resource, action] = key.split(':');
  return { resource, action };
}
